- name: Install and configure Zabbix server and agent
  hosts: zabbix_server
  become: true

  tasks:
    # Install required packages
    - name: Install Apache httpd
      package:
        name: httpd
        state: present

    - name: Configure SSL/TLS for Apache httpd
      vars:
        server_name: zabbix.example.com
        ssl_cert: /etc/pki/tls/certs/zabbix.example.com.crt
        ssl_key: /etc/pki/tls/private/zabbix.example.com.key
      template:
        src: templates/httpd_ssl.conf.j2
        dest: /etc/httpd/conf.d/ssl.conf
      notify: Restart httpd

    - name: Install PHP and required modules
      package:
        name:
          - php
          - php-mysqlnd
          - php-gd
          - php-xml
          - php-bcmath
          - php-ldap
        state: present

    - name: Install MariaDB server
      package:
        name: mariadb-server
        state: present

    # Add Zabbix repository
    - name: Add Zabbix repository
      dnf:
        name: https://repo.zabbix.com/zabbix/6.0/rhel/9/x86_64/zabbix-release-6.0-3.el9.noarch.rpm
        state: present

    # Install Zabbix server and agent
    - name: Install Zabbix server and agent
      package:
        name:
          - zabbix-server-mysql
          - zabbix-web-mysql
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-selinux-policy
          - zabbix-agent2
        state: present

    # Create a database for Zabbix
    - name: Create database for Zabbix
      mysql_db:
        name: zabbix
        state: present
        collation: utf8mb4_bin
        encoding: utf8mb4
        login_host: localhost
        login_user: zabbix
        login_password: "{{ zabbix_db_password }}"

    # Import Zabbix database schema
    - name: Import Zabbix database schema
      become_user: zabbix
      command: zcat /usr/share/zabbix-sql-scripts/mysql/schema.sql.gz | mysql -uzabbix -p{{ zabbix_db_password }} zabbix
      args:
        creates: /var/lib/mysql/zabbix

    # Import Zabbix database data
    - name: Import Zabbix database data
      become_user: zabbix
      command: zcat /usr/share/zabbix-sql-scripts/mysql/images.sql.gz | mysql -uzabbix -p{{ zabbix_db_password }} zabbix
      args:
        creates: /var/lib/mysql/zabbix/images.ibd

    - name: Import Zabbix database data
      become_user: zabbix
      command: zcat /usr/share/zabbix-sql-scripts/mysql/data.sql.gz | mysql -uzabbix -p{{ zabbix_db_password }} zabbix
      args:
        creates: /var/lib/mysql/zabbix/history.ibd

    # Configure Zabbix server
    - name: Configure Zabbix server
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: "^DBHost.*", line: "DBHost=localhost" }
        - { regexp: "^DBPassword.*", line: "DBPassword={{ zabbix_db_password }}" }

    # Start Zabbix server
    - name: Start Zabbix server
      service:
        name: zabbix-server
        state: started
        enabled: true

    # Configure Zabbix agent
    - name: Configure Zabbix agent
      lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: "^ServerActive.*", line: "ServerActive=127.0.0.1" }
        - { regexp: "^Hostname.*", line: "Hostname={{ inventory_hostname }}" }

    # Start Zabbix agent
    - name: Start Zabbix agent
      service:
        name: zabbix-agent2
        state: started
        enabled: true

  handlers:
    # Restart httpd
    - name: Restart httpd
      service:
        name: httpd
        state: restarted